# Site settings
title: Brilliant Documentation
description: Technical documentation for all the Brilliant products.
logo: /images/logo.svg
remote_theme: just-the-docs/just-the-docs
color_scheme: brilliant
permalink: pretty
heading_anchors: true
url: https://docs.brilliant.xyz

# Plugins
plugins:
  - jekyll-include-cache
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

# Header
search_enabled: true
aux_links_new_tab: true
aux_links:
  YouTube:
    - https://www.youtube.com/@brilliantlabsAR
  Discord:
    - https://discord.com/invite/vDS9X7gdwg
  GitHub:
    - https://github.com/brilliantlabsAR
  Homepage:
    - https://www.brilliant.xyz

# Footer
footer_content: Copyright &copy; 2024 <a href="https://www.brilliant.xyz">Brilliant Labs</a>
last_edit_timestamp: true
last_edit_time_format: "%b %e %Y"

# Mermaid diagrams
mermaid:
  version: "9.2.2" # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/

# Call-outs 
callouts:
  warning:
    title: Caution
    color: red
  note:
    title: Note
    color: blue

# SEO settings
twitter:
  username: opensourceeyes
  # card:
social:
  name: Brilliant Labs
  links:
    - https://twitter.com/opensourceeyes
    - https://www.instagram.com/opensourceeyes/
    - https://discord.com/invite/vDS9X7gdwg

# Google analytics
# ga_tracking: UA-162687810-2
# ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings

# Exclude files
exclude:
  - CNAME
  - Gemfile
  - README.md
  - LICENSE.md

# Optimizations
compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
